---
- hosts: webservers
  become: true

  tasks:
    - name: update package
      apt:
        update_cache: yes
        state: latest

    - name: install nginx
      apt:
        name: nginx
        state: latest
